version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20.0

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules

  test:
    executor: node-executor
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
